import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about";
import Contact from "../components/contact";
import Projects from "../components/projects";
import Techonologies from "../components/technologies";
import TopCover from "../components/topcover";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>facuariasla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#272727"/>
        <link rel="icon" href="/assets/afwhitewbg.png" />
      </Head>

      <div>
        <TopCover/>
        <About/>
        <Techonologies/>
        <Projects/>
        <Contact/>
      </div>
    </div>
  );
};

export default Home;
